apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: api-pipeline
  source:
    path: sealed-secrets
    repoURL: https://github.com/claudioed/argo-api-pipeline.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
      prune: true